version: 2
jobs:
  build:
    docker:
      - image: ajoberstar/circleci-openjdk-gradle:8-jdk
    steps:
      - checkout
      - run:
          name: Compile and test
          command: ./gradlew clean check --continue --stacktrace
      - store_test_results:
          path: ~/gradle-test-results
          when: always
