defaults: &defaults
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-gradle-{{ checksum "global.lock" }}-{{ checksum "build.gradle" }}
          - v1-gradle--
    - run:
        name: Compile and test
        command: ./gradlew clean check lintGradle
    - save_cache:
        paths:
          - ~/.gradle
        key: v1-gradle-{{ checksum "global.lock" }}-{{ checksum "build.gradle" }}
tags-only: &tags-only
  branches:
    ignore: /.*/
  tags:
    only: /^\d+\.\d+\.\d(?:-.+)?$/


version: 2
jobs:
  commit-java-lts:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk
  commit-java-9:
    <<: *defaults
    docker:
      - image: circleci/openjdk:9-jdk
  commit-java-10:
    <<: *defaults
    docker:
      - image: circleci/openjdk:10-jdk
  publish:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-{{ checksum "global.lock" }}-{{ checksum "build.gradle" }}
      - run:
          name: Compile and test
          command: ./gradlew clean check
      - run:
          name: Publish Artifacts
          command: ./gradlew reckonTagPush publish publishPlugins gitPublishPush
workflows:
  version: 2
  main:
    jobs:
      - commit-java-lts
      - commit-java-9:
          requires:
            - commit-java-lts
      - commit-java-10:
          requires:
            - commit-java-lts
      - request-publish:
          type: approval
          requires:
            - commit-java-lts
            - commit-java-9
            - commit-java-10
          filters:
            <<: *tags-only
      - publish:
          requires:
            - request-publish
          context: ajoberstar
          filters:
            <<: *tags-only
