defaults: &defaults
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-gradle-{{ .Revision }}
    - run:
        name: Compile and test
        command: ./gradlew clean check
    - store_test_results:
        path: build/test-results
        when: always
branches-and-tags: &branches-and-tags
  filters:
    tags:
      only: /^\d+\.\d+\.\d(?:-.+)?$/
tags-only: &tags-only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^\d+\.\d+\.\d(?:-.+)?$/

version: 2
jobs:
  cache-dependencies:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-{{ .Revision }}
      - run:
          name: Download dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-gradle-{{ .Revision }}
  update-dependencies:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-{{ .Revision }}
      - run:
          name: Update dependencies
          command: ./gradlew dependencies --write-locks
      - run:
          name: Diff lockfiles
          command: git diff
  build-java-8:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk
  build-java-9:
    <<: *defaults
    docker:
      - image: circleci/openjdk:9-jdk
  build-java-10:
    <<: *defaults
    docker:
      - image: circleci/openjdk:10-jdk
  publish:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-{{ .Revision }}
      - run:
          name: Publish Artifacts
          command: ./gradlew publish gitPublishPush
workflows:
  version: 2
  main:
    jobs:
      - cache-dependencies:
          <<: *branches-and-tags
      - build-java-8:
          <<: *branches-and-tags
          requires:
            - cache-dependencies
      - build-java-9:
          <<: *branches-and-tags
          requires:
            - cache-dependencies
      - build-java-10:
          <<: *branches-and-tags
          requires:
            - cache-dependencies
      - publish:
          <<: *tags-only
          requires:
            - build-java-8
            - build-java-9
            - build-java-10
          context: ajoberstar
  dependencies:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - update-dependencies
  temp:
    jobs:
      - update-dependencies:
          context: ajoberstar
