on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 13]
    steps:
      - uses: "actions/checkout@master"
      - uses: "actions/setup-java@master"
        with:
          java-version: ${{ matrix.java }}
      - run: "./gradlew check"
