on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 13]
    steps:
      - uses: "actions/checkout"
      - uses: "./.github/actions/openjdk"
