on:
  push:
    tags:
      - "*"
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
      fail-fast: false
    steps:
      - uses: "actions/checkout@master"
      - uses: "actions/setup-java@master"
        with:
          java-version: ${{ matrix.java }}
      - run: "./gradlew check --continue"
  publish:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: "actions/checkout@master"
      - uses: "actions/setup-java@master"
        with:
          java-version: 11
      - name: "Gradle publish"
        env:
          ORG_GRADLE_PROJECT_PUBLISH_KEY: ${{ secrets.gradle-plugin-key }}
          ORG_GRADLE_PROJECT_PUBLISH_SECRET: ${{ secrets.gradle-plugin-secret }}
        run: "./gradlew publish publishPlugins"
